### PR TITLE
Add heartbeat support, expose persistent ids

### PR DESCRIPTION
**Pull request by koush**
This add support for heartbeat. Without this, there's no way to know if the push receiver has died due to TCP timeout on some platforms with long keepalive intervals. For example, Linux has a 2 hour interval before it sends the keep alive probe.

### CODE REVIEW

**Comment by Eneris** [comment]
Good work thanks

**Comment by Eneris** [comment]
Thanks for your work :)
Could you please finish the work with the protobuf? I see that you've replaced the module, but code is not updated.

**Comment by koush** [comment]
Not sure what that was about. Had a build issue that I thought was resolved by that, but it doesn't seem to affect it. It's just a cli wrapper for protobufjs. Removed it anyways.

**Comment by Eneris** [comment]
That seems to be a breaking change in protobufjs package from v7. They are splitting their cli from package.
I'll take your code and do some more integrating. Thanks

**Comment by koush** [comment]
In case you missed it, I removed that protobuf package change, so this pull request should be clean.

**Comment by Eneris** [comment]
Yes. Got it. Also, could you please add some test cases in jest that could verify if heartbeat is actually working?
Here is a branch with some changes to your PR

**Comment by Eneris** [comment]
Also. You sem to commited `package-lock.json` along with the `yarn.lock`. There must be only one and that is `yarn.lock`

**Comment by Eneris** [comment]
@koush I've resolved this PR in other branch based on the changes you've provided. Thank you.
Please check out the version 3.1.0 . Hope it works for you.

**Pull request closed without merging**
