### PR TITLE
Retry socket connection even when connect fails

### PR DESCRIPTION
**Pull request by tsightler**
Hi @Eneris,

This PR is my attempt to fix https://github.com/Eneris/push-receiver/issues/28.  This will retry even in cases where connect fails completely (for example, no network connectivity) and I also added a catch so that the rejected promise in `#clearReady` does not cause an unhandled rejection warning.

Testing so far shows this solves the issue, reconnect happens within 15 seconds after the network connection recovers, even if the connection is down for several hours.

### CODE REVIEW

**Comment by Eneris** [comment]
Hi. While reading your PR, I figured out how to split network errors in requests and retry them until they succeed or return non-network error. Let me know if that works for your problem
https://github.com/Eneris/push-receiver/commit/9abb2ca3fb1d5b322aa94b4c226bf7d8fa5f4cc2

**Comment by tsightler** [comment]
@Eneris I will try with your patch this weekend.  Quite honestly, that was my first idea, but I was concerned that it could lead to the initial `connect()` call made by the client to hang forever if the network was unavailable and I wasn't sure if that was desired behavior or not, which is why I implemented it using socket retry logic instead, as that only kicks in if initial connection was successful.

**Comment by Eneris** [comment]
I'd say. it's ok if it's network error

**Comment by tsightler** [comment]
I gave https://github.com/Eneris/push-receiver/commit/9abb2ca3fb1d5b322aa94b4c226bf7d8fa5f4cc2 a try and it seems to address the issue.  Appreciate you looking at it.  I'll close this PR for now and wait for you to get a new package pushed.

**Comment by Eneris** [comment]
Ok. Thanks for testing :)

**Pull request closed without merging**
